-- Migración original de bookmarks. Supersedida por 20260703120000_create_user_content.sql
-- que unifica favorites, bookmarks y watched en la tabla user_content.
-- Este archivo se mantiene para conservar el historial de migraciones.
